In [131]:
#Importo las librerias
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.preprocessing import StandardScaler
import matplotlib as plot
import pandas as pd
import numpy as np

In [97]:
archivo = 'datos taller4.xls'
df = pd.read_excel(archivo, sheet_name=1)
df

,ID,YEAR_STA,TARGET,WHERE,REGIOTYP,BUYPOWER,CASATYP,STRTYP,VAL_TIER,FAMGROUP,...,TYP7,TYP8,TYP9,PROB_DAILY,PHARM1,PHARM2,PHARM3,PHARM4,PHARM5,PHARM6
0,389155,1997,0,0.0,15.0,3.0,1.0,1.0,5.0,7.0,...,1.0,1.0,1.0,4.0,1.0,7.0,1.0,6.0,1.0,5.0
1,102389,1975,0,0.0,12.0,1.0,1.0,1.0,5.0,8.0,...,6.0,6.0,7.0,8.0,1.0,6.0,2.0,7.0,4.0,2.0
2,361340,1996,0,1.0,16.0,-9.0,1.0,1.0,4.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,35454,1989,0,0.0,12.0,3.0,1.0,4.0,1.0,5.0,...,6.0,4.0,4.0,6.0,6.0,5.0,3.0,6.0,2.0,4.0
4,24470,1993,0,0.0,16.0,7.0,2.0,1.0,8.0,6.0,...,1.0,7.0,7.0,1.0,6.0,3.0,2.0,5.0,2.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,308579,1995,1,0.0,13.0,2.0,2.0,4.0,8.0,4.0,...,6.0,5.0,3.0,1.0,7.0,6.0,1.0,6.0,4.0,1.0
8996,250154,1994,1,0.0,16.0,3.0,1.0,3.0,8.0,7.0,...,6.0,2.0,4.0,2.0,1.0,3.0,7.0,2.0,7.0,1.0
8997,56316,1992,1,0.0,13.0,7.0,3.0,1.0,7.0,5.0,...,5.0,3.0,4.0,1.0,4.0,1.0,2.0,4.0,7.0,5.0
8998,333801,1996,1,0.0,12.0,7.0,1.0,4.0,2.0,9.0,...,7.0,7.0,7.0,7.0,4.0,2.0,6.0,7.0,2.0,5.0
8999,327203,1996,1,0.0,15.0,5.0,2.0,1.0,9.0,7.0,...,5.0,1.0,7.0,1.0,5.0,5.0,4.0,7.0,2.0,4.0

In [161]:
#leo el archivo
#Usaré solo el train porque test no posee columna 'TARGET' para evaluar resultados
archivo = 'datos taller4.xls'
df = pd.read_excel(archivo, sheet_name=1)
df = df.dropna() #Borramos valores nulos
clase = df['TARGET']
df = df.drop(['ID','TARGET'],axis=1)#Borramos la primera columna

#Se crea el conjunto de entrenamiento y testeo
data_train , data_test , clase_train , clase_test = \
    train_test_split(df, clase,
                    test_size = 0.1, random_state=88)

In [162]:
#Transformamos los datos
standard_x = StandardScaler()
data_train = standard_x.fit_transform(data_train)
data_test = standard_x.fit_transform(data_test)

In [163]:
#Se crea el modelo de Regresión Logística
modelo = LogisticRegression(random_state=88).fit(data_train , clase_train)
#Suprimimos lanotación científica
np.set_printoptions(suppress=True)

In [164]:
#Genero la predicción con el conjunto de testeo
pred = modelo.predict(data_test)
pred

array([1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1], dtype=int64)

In [165]:
#Matriz de confusión
conf_mat = confusion_matrix(clase_test, pred)
conf_mat

array([[166, 156],
       [103, 271]], dtype=int64)

In [166]:
#Métricas
accuracy = accuracy_score(clase_test, pred) *100
precision = precision_score(clase_test, pred)*100
recall = recall_score(clase_test, pred)
print('Accuracy: %.2f%% '% accuracy,
     "\nPrecision: %2.2f%% "% precision,
     "\nRecall: %2.2f%%" % recall)
#  Recall: indica la proporción de ejemplos positivos 
# que están identificados correctamente por el modelo entre todos los positivos reales

Accuracy: 62.79%
Precision: 63.47%
Recall: 0.72%

In [181]:
#Ahora probamos con el df test orginal (primera hoja del excel que no tiene 'TARGET')
df_p = pd.read_excel(archivo, sheet_name=0)
#Quitamos la columna de ID porque no tiene importancia
df_p1 = df_p.iloc[:,1:]
df_p = df_p.dropna()
df_p1 = df_p1.dropna()
#Estandarizamos
df_p1 = standard_x.fit_transform(df_p1)
#Corremos el predictor y vemos las predicciones para posteriormente
#Agregarlas al dataframe
pred2 = modelo.predict(df_p1)
#Quedandonos algo así
df_p['TARGET'] = pred2
df_p
#Agregando la nueva columna con la predicción correspondiente

,ID,YEAR_STA,WHERE,REGIOTYP,BUYPOWER,CASATYP,STRTYP,VAL_TIER,FAMGROUP,AGEGROUP,...,TYP8,TYP9,PROB_DAILY,PHARM1,PHARM2,PHARM3,PHARM4,PHARM5,PHARM6,TARGET
0,28306,1992,0.0,11.0,8.0,5.0,1.0,5.0,2.0,4.0,...,2.0,7.0,2.0,5.0,6.0,2.0,3.0,6.0,2.0,0
1,241585,1994,0.0,13.0,2.0,1.0,4.0,5.0,5.0,5.0,...,1.0,1.0,3.0,1.0,6.0,2.0,6.0,1.0,3.0,1
3,368506,1996,0.0,11.0,7.0,2.0,1.0,9.0,1.0,5.0,...,1.0,5.0,5.0,1.0,6.0,3.0,7.0,2.0,6.0,1
4,374891,1997,0.0,13.0,4.0,1.0,1.0,1.0,7.0,4.0,...,3.0,7.0,7.0,7.0,5.0,5.0,3.0,4.0,2.0,1
5,321433,1996,0.0,12.0,8.0,2.0,1.0,3.0,3.0,5.0,...,2.0,2.0,2.0,5.0,2.0,4.0,4.0,1.0,7.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,384475,1997,0.0,12.0,9.0,1.0,3.0,1.0,9.0,4.0,...,3.0,6.0,3.0,7.0,4.0,6.0,1.0,1.0,5.0,0
995,368503,1996,0.0,11.0,6.0,4.0,1.0,9.0,8.0,4.0,...,5.0,5.0,4.0,4.0,6.0,6.0,2.0,7.0,2.0,1
996,284643,1995,0.0,16.0,1.0,2.0,3.0,8.0,7.0,4.0,...,2.0,5.0,1.0,5.0,6.0,1.0,1.0,4.0,5.0,1
997,354426,1996,0.0,15.0,7.0,2.0,2.0,7.0,4.0,4.0,...,1.0,2.0,1.0,5.0,1.0,5.0,5.0,4.0,7.0,1
999,365765,1996,0.0,16.0,3.0,0.0,1.0,3.0,6.0,3.0,...,2.0,6.0,3.0,3.0,4.0,7.0,2.0,6.0,2.0,1